version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: lotofacil
      POSTGRES_PASSWORD: lotofacil
      POSTGRES_DB: lotofacil
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://lotofacil:lotofacil@postgres:5432/lotofacil
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_KEY: ${NEXT_PUBLIC_SUPABASE_KEY}
      API_BASE_URL: http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  pgdata:
